/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsVehiclesRouteImport } from './routes/settings/vehicles'
import { Route as SettingsPersonalInfoRouteImport } from './routes/settings/personal-info'
import { Route as SettingsDataPrivacyRouteImport } from './routes/settings/data-privacy'
import { Route as SettingsAccountsRouteImport } from './routes/settings/accounts'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsVehiclesRoute = SettingsVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPersonalInfoRoute = SettingsPersonalInfoRouteImport.update({
  id: '/personal-info',
  path: '/personal-info',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataPrivacyRoute = SettingsDataPrivacyRouteImport.update({
  id: '/data-privacy',
  path: '/data-privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountsRoute = SettingsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsRoute
  '/evolution': typeof EvolutionRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/data-privacy': typeof SettingsDataPrivacyRoute
  '/settings/personal-info': typeof SettingsPersonalInfoRoute
  '/settings/vehicles': typeof SettingsVehiclesRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsRoute
  '/evolution': typeof EvolutionRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof TransactionsRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/data-privacy': typeof SettingsDataPrivacyRoute
  '/settings/personal-info': typeof SettingsPersonalInfoRoute
  '/settings/vehicles': typeof SettingsVehiclesRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budgets': typeof BudgetsRoute
  '/evolution': typeof EvolutionRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/settings/accounts': typeof SettingsAccountsRoute
  '/settings/data-privacy': typeof SettingsDataPrivacyRoute
  '/settings/personal-info': typeof SettingsPersonalInfoRoute
  '/settings/vehicles': typeof SettingsVehiclesRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budgets'
    | '/evolution'
    | '/goals'
    | '/import'
    | '/login'
    | '/more'
    | '/register'
    | '/settings'
    | '/transactions'
    | '/settings/accounts'
    | '/settings/data-privacy'
    | '/settings/personal-info'
    | '/settings/vehicles'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budgets'
    | '/evolution'
    | '/goals'
    | '/import'
    | '/login'
    | '/more'
    | '/register'
    | '/transactions'
    | '/settings/accounts'
    | '/settings/data-privacy'
    | '/settings/personal-info'
    | '/settings/vehicles'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/budgets'
    | '/evolution'
    | '/goals'
    | '/import'
    | '/login'
    | '/more'
    | '/register'
    | '/settings'
    | '/transactions'
    | '/settings/accounts'
    | '/settings/data-privacy'
    | '/settings/personal-info'
    | '/settings/vehicles'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetsRoute: typeof BudgetsRoute
  EvolutionRoute: typeof EvolutionRoute
  GoalsRoute: typeof GoalsRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/vehicles': {
      id: '/settings/vehicles'
      path: '/vehicles'
      fullPath: '/settings/vehicles'
      preLoaderRoute: typeof SettingsVehiclesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/personal-info': {
      id: '/settings/personal-info'
      path: '/personal-info'
      fullPath: '/settings/personal-info'
      preLoaderRoute: typeof SettingsPersonalInfoRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data-privacy': {
      id: '/settings/data-privacy'
      path: '/data-privacy'
      fullPath: '/settings/data-privacy'
      preLoaderRoute: typeof SettingsDataPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/accounts': {
      id: '/settings/accounts'
      path: '/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof SettingsAccountsRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAccountsRoute: typeof SettingsAccountsRoute
  SettingsDataPrivacyRoute: typeof SettingsDataPrivacyRoute
  SettingsPersonalInfoRoute: typeof SettingsPersonalInfoRoute
  SettingsVehiclesRoute: typeof SettingsVehiclesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountsRoute: SettingsAccountsRoute,
  SettingsDataPrivacyRoute: SettingsDataPrivacyRoute,
  SettingsPersonalInfoRoute: SettingsPersonalInfoRoute,
  SettingsVehiclesRoute: SettingsVehiclesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetsRoute: BudgetsRoute,
  EvolutionRoute: EvolutionRoute,
  GoalsRoute: GoalsRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
