export interface VehicleBrand {
  id: string;
  name: string;
  iconUrl: string;
}

export const SUPPORTED_BRANDS: VehicleBrand[] = [
  // Carros - Populares, Premium, Luxo e Elétricos
  { id: 'ABARTH', name: 'Abarth', iconUrl: 'https://cdn.simpleicons.org/abarth' },
  { id: 'ACURA', name: 'Acura', iconUrl: 'https://cdn.simpleicons.org/acura' },
  { id: 'ALFA_ROMEO', name: 'Alfa Romeo', iconUrl: 'https://cdn.simpleicons.org/alfaromeo' },
  { id: 'ALPINE', name: 'Alpine', iconUrl: 'https://cdn.simpleicons.org/alpine' },
  { id: 'ASTON_MARTIN', name: 'Aston Martin', iconUrl: 'https://cdn.simpleicons.org/astonmartin' },
  { id: 'AUDI', name: 'Audi', iconUrl: 'https://cdn.simpleicons.org/audi' },
  { id: 'BENTLEY', name: 'Bentley', iconUrl: 'https://cdn.simpleicons.org/bentley' },
  { id: 'BMW', name: 'BMW', iconUrl: 'https://cdn.simpleicons.org/bmw' },
  { id: 'BUGATTI', name: 'Bugatti', iconUrl: 'https://cdn.simpleicons.org/bugatti' },
  { id: 'BYD', name: 'BYD', iconUrl: 'https://cdn.simpleicons.org/byd' },
  { id: 'CADILLAC', name: 'Cadillac', iconUrl: 'https://cdn.simpleicons.org/cadillac' },
  { id: 'CHEVROLET', name: 'Chevrolet', iconUrl: 'https://cdn.simpleicons.org/chevrolet' },
  { id: 'CHRYSLER', name: 'Chrysler', iconUrl: 'https://cdn.simpleicons.org/chrysler' },
  { id: 'CITROEN', name: 'Citroën', iconUrl: 'https://cdn.simpleicons.org/citroen' },
  { id: 'CUPRA', name: 'Cupra', iconUrl: 'https://cdn.simpleicons.org/cupra' },
  { id: 'DACIA', name: 'Dacia', iconUrl: 'https://cdn.simpleicons.org/dacia' },
  { id: 'DAIHATSU', name: 'Daihatsu', iconUrl: 'https://cdn.simpleicons.org/daihatsu' },
  { id: 'DODGE', name: 'Dodge', iconUrl: 'https://cdn.simpleicons.org/dodge' },
  { id: 'DS', name: 'DS Automobiles', iconUrl: 'https://cdn.simpleicons.org/ds' },
  { id: 'FERRARI', name: 'Ferrari', iconUrl: 'https://cdn.simpleicons.org/ferrari' },
  { id: 'FIAT', name: 'Fiat', iconUrl: 'https://cdn.simpleicons.org/fiat' },
  { id: 'FISKER', name: 'Fisker', iconUrl: 'https://cdn.simpleicons.org/fisker' },
  { id: 'FORD', name: 'Ford', iconUrl: 'https://cdn.simpleicons.org/ford' },
  { id: 'GENESIS', name: 'Genesis', iconUrl: 'https://cdn.simpleicons.org/genesis' },
  { id: 'GMC', name: 'GMC', iconUrl: 'https://cdn.simpleicons.org/gmc' },
  { id: 'GWM', name: 'GWM', iconUrl: 'https://cdn.simpleicons.org/gwm' },
  { id: 'HONDA', name: 'Honda', iconUrl: 'https://cdn.simpleicons.org/honda' },
  { id: 'HUMMER', name: 'Hummer', iconUrl: 'https://cdn.simpleicons.org/hummer' },
  { id: 'HYUNDAI', name: 'Hyundai', iconUrl: 'https://cdn.simpleicons.org/hyundai' },
  { id: 'INFINITI', name: 'Infiniti', iconUrl: 'https://cdn.simpleicons.org/infiniti' },
  { id: 'ISUZU', name: 'Isuzu', iconUrl: 'https://cdn.simpleicons.org/isuzu' },
  { id: 'JAC', name: 'JAC Motors', iconUrl: 'https://cdn.simpleicons.org/jac' },
  { id: 'JAGUAR', name: 'Jaguar', iconUrl: 'https://cdn.simpleicons.org/jaguar' },
  { id: 'JEEP', name: 'Jeep', iconUrl: 'https://cdn.simpleicons.org/jeep' },
  { id: 'KIA', name: 'Kia', iconUrl: 'https://cdn.simpleicons.org/kia' },
  { id: 'KOENIGSEGG', name: 'Koenigsegg', iconUrl: 'https://cdn.simpleicons.org/koenigsegg' },
  { id: 'LAMBORGHINI', name: 'Lamborghini', iconUrl: 'https://cdn.simpleicons.org/lamborghini' },
  { id: 'LANCIA', name: 'Lancia', iconUrl: 'https://cdn.simpleicons.org/lancia' },
  { id: 'LAND_ROVER', name: 'Land Rover', iconUrl: 'https://cdn.simpleicons.org/landrover' },
  { id: 'LEXUS', name: 'Lexus', iconUrl: 'https://cdn.simpleicons.org/lexus' },
  { id: 'LINCOLN', name: 'Lincoln', iconUrl: 'https://cdn.simpleicons.org/lincoln' },
  { id: 'LOTUS', name: 'Lotus', iconUrl: 'https://cdn.simpleicons.org/lotus' },
  { id: 'LUCID', name: 'Lucid Motors', iconUrl: 'https://cdn.simpleicons.org/lucid' },
  { id: 'MAHINDRA', name: 'Mahindra', iconUrl: 'https://cdn.simpleicons.org/mahindra' },
  { id: 'MASERATI', name: 'Maserati', iconUrl: 'https://cdn.simpleicons.org/maserati' },
  { id: 'MAZDA', name: 'Mazda', iconUrl: 'https://cdn.simpleicons.org/mazda' },
  { id: 'MCLAREN', name: 'McLaren', iconUrl: 'https://cdn.simpleicons.org/mclaren' },
  { id: 'MERCEDES', name: 'Mercedes-Benz', iconUrl: 'https://cdn.simpleicons.org/mercedes' },
  { id: 'MINI', name: 'Mini', iconUrl: 'https://cdn.simpleicons.org/mini' },
  { id: 'MITSUBISHI', name: 'Mitsubishi', iconUrl: 'https://cdn.simpleicons.org/mitsubishi' },
  { id: 'NIO', name: 'NIO', iconUrl: 'https://cdn.simpleicons.org/nio' },
  { id: 'NISSAN', name: 'Nissan', iconUrl: 'https://cdn.simpleicons.org/nissan' },
  { id: 'OPEL', name: 'Opel', iconUrl: 'https://cdn.simpleicons.org/opel' },
  { id: 'PAGANI', name: 'Pagani', iconUrl: 'https://cdn.simpleicons.org/pagani' },
  { id: 'PEUGEOT', name: 'Peugeot', iconUrl: 'https://cdn.simpleicons.org/peugeot' },
  { id: 'POLESTAR', name: 'Polestar', iconUrl: 'https://cdn.simpleicons.org/polestar' },
  { id: 'PORSCHE', name: 'Porsche', iconUrl: 'https://cdn.simpleicons.org/porsche' },
  { id: 'RAM', name: 'RAM', iconUrl: 'https://cdn.simpleicons.org/ram' },
  { id: 'RENAULT', name: 'Renault', iconUrl: 'https://cdn.simpleicons.org/renault' },
  { id: 'RIVIAN', name: 'Rivian', iconUrl: 'https://cdn.simpleicons.org/rivian' },
  { id: 'ROLLS_ROYCE', name: 'Rolls-Royce', iconUrl: 'https://cdn.simpleicons.org/rollsroyce' },
  { id: 'SAAB', name: 'Saab', iconUrl: 'https://cdn.simpleicons.org/saab' },
  { id: 'SEAT', name: 'Seat', iconUrl: 'https://cdn.simpleicons.org/seat' },
  { id: 'SKODA', name: 'Skoda', iconUrl: 'https://cdn.simpleicons.org/skoda' },
  { id: 'SMART', name: 'Smart', iconUrl: 'https://cdn.simpleicons.org/smart' },
  { id: 'SSANGYONG', name: 'SsangYong', iconUrl: 'https://cdn.simpleicons.org/ssangyong' },
  { id: 'SUBARU', name: 'Subaru', iconUrl: 'https://cdn.simpleicons.org/subaru' },
  { id: 'SUZUKI', name: 'Suzuki', iconUrl: 'https://cdn.simpleicons.org/suzuki' },
  { id: 'TATA', name: 'Tata', iconUrl: 'https://cdn.simpleicons.org/tata' },
  { id: 'TESLA', name: 'Tesla', iconUrl: 'https://cdn.simpleicons.org/tesla' },
  { id: 'TOYOTA', name: 'Toyota', iconUrl: 'https://cdn.simpleicons.org/toyota' },
  { id: 'VAUXHALL', name: 'Vauxhall', iconUrl: 'https://cdn.simpleicons.org/vauxhall' },
  { id: 'VINFAST', name: 'VinFast', iconUrl: 'https://cdn.simpleicons.org/vinfast' },
  { id: 'VOLKSWAGEN', name: 'Volkswagen', iconUrl: 'https://cdn.simpleicons.org/volkswagen' },
  { id: 'VOLVO', name: 'Volvo', iconUrl: 'https://cdn.simpleicons.org/volvo' },
  { id: 'XPENG', name: 'XPeng', iconUrl: 'https://cdn.simpleicons.org/xpeng' },

  // Motos
  { id: 'APRILIA', name: 'Aprilia', iconUrl: 'https://cdn.simpleicons.org/aprilia' },
  { id: 'BAJAJ', name: 'Bajaj', iconUrl: 'https://cdn.simpleicons.org/bajaj' },
  { id: 'BENELLI', name: 'Benelli', iconUrl: 'https://cdn.simpleicons.org/benelli' },
  { id: 'DUCATI', name: 'Ducati', iconUrl: 'https://cdn.simpleicons.org/ducati' },
  { id: 'GASGAS', name: 'GASGAS', iconUrl: 'https://cdn.simpleicons.org/gasgas' },
  {
    id: 'HARLEY_DAVIDSON',
    name: 'Harley-Davidson',
    iconUrl: 'https://cdn.simpleicons.org/harleydavidson',
  },
  { id: 'HERO', name: 'Hero MotoCorp', iconUrl: 'https://cdn.simpleicons.org/heromotocorp' },
  { id: 'HONDA_MOTO', name: 'Honda Motos', iconUrl: 'https://cdn.simpleicons.org/honda' },
  { id: 'HUSQVARNA', name: 'Husqvarna', iconUrl: 'https://cdn.simpleicons.org/husqvarna' },
  {
    id: 'INDIAN',
    name: 'Indian Motorcycle',
    iconUrl: 'https://cdn.simpleicons.org/indianmotorcycle',
  },
  { id: 'KAWASAKI', name: 'Kawasaki', iconUrl: 'https://cdn.simpleicons.org/kawasaki' },
  { id: 'KTM', name: 'KTM', iconUrl: 'https://cdn.simpleicons.org/ktm' },
  { id: 'KYMCO', name: 'Kymco', iconUrl: 'https://cdn.simpleicons.org/kymco' },
  { id: 'MOTO_GUZZI', name: 'Moto Guzzi', iconUrl: 'https://cdn.simpleicons.org/motoguzzi' },
  { id: 'MV_AGUSTA', name: 'MV Agusta', iconUrl: 'https://cdn.simpleicons.org/mvagusta' },
  { id: 'PIAGGIO', name: 'Piaggio', iconUrl: 'https://cdn.simpleicons.org/piaggio' },
  {
    id: 'ROYAL_ENFIELD',
    name: 'Royal Enfield',
    iconUrl: 'https://cdn.simpleicons.org/royalenfield',
  },
  { id: 'SYM', name: 'SYM', iconUrl: 'https://cdn.simpleicons.org/sym' },
  { id: 'TRIUMPH', name: 'Triumph', iconUrl: 'https://cdn.simpleicons.org/triumph' },
  { id: 'VESPA', name: 'Vespa', iconUrl: 'https://cdn.simpleicons.org/vespa' },
  { id: 'YAMAHA', name: 'Yamaha', iconUrl: 'https://cdn.simpleicons.org/yamaha' },

  // Caminhões / Pesados
  { id: 'DAF', name: 'DAF', iconUrl: 'https://cdn.simpleicons.org/daf' },
  { id: 'FREIGHTLINER', name: 'Freightliner', iconUrl: 'https://cdn.simpleicons.org/freightliner' },
  { id: 'HINO', name: 'Hino', iconUrl: 'https://cdn.simpleicons.org/hino' },
  { id: 'IVECO', name: 'Iveco', iconUrl: 'https://cdn.simpleicons.org/iveco' },
  { id: 'KENWORTH', name: 'Kenworth', iconUrl: 'https://cdn.simpleicons.org/kenworth' },
  { id: 'MACK', name: 'Mack Trucks', iconUrl: 'https://cdn.simpleicons.org/mack' },
  { id: 'MAN', name: 'MAN', iconUrl: 'https://cdn.simpleicons.org/man' },
  { id: 'PETERBILT', name: 'Peterbilt', iconUrl: 'https://cdn.simpleicons.org/peterbilt' },
  { id: 'SCANIA', name: 'Scania', iconUrl: 'https://cdn.simpleicons.org/scania' },
  { id: 'WESTERN_STAR', name: 'Western Star', iconUrl: 'https://cdn.simpleicons.org/westernstar' },
].sort((a, b) => a.name.localeCompare(b.name));

export function getBrandIcon(brandId?: string) {
  const brand = SUPPORTED_BRANDS.find((b) => b.id === brandId);
  return brand?.iconUrl;
}
